### ISSUE TITLE
Abandoned Repo

### ISSUE THREAD

**Issue by KenCox94** [bryanyang0528/ksql-python#110]
I've contacted the owner of this repo via LinkedIn since he has yet to make any updates ( pull requests, commits, etc ) over the past year.

I will give it a week and then, depending on how the community feels I will attempt to take ownership following [ these steps ](https://github.community/t/what-is-github-policy-about-abandoned-repositories/117668/2)

Please let me know how you feel about this. I regularly use this library and it would be a shame to let it idle and eventually die. 

Tagging contributors 
---------------
@romainr 
@kaiwaehner 
@lucrussell 
@jurieotto 
@harlev 
@dimino 
@sebastianneubauer

**Comment by sebastianneubauer** [comment]
Fully supportive +1

**Comment by romainr** [comment]
+1

**Comment by KenCox94** [comment]
The owner has contacted me. He was unaware of the popularity of this project. 
I am being made a maintainer and it appears that pull request are being merged.
