### ISSUE TITLE
add debug mode for sql query

### ISSUE THREAD

**Issue by bryanyang0528** [bryanyang0528/ksql-python#19]

**Comment by maulikjs** [comment]
What do you mean by this?
Interactive mode? 
Like type a query and get the O/P? and type another one? I can maybe work on this too

**Comment by bryanyang0528** [comment]
In the current version, there hasn't any logging mechanism. It filtered all raw messages from the KSQL server and can't be seen by users or developers, so it's really hard to debug or test.  I'm used to using logging to manage logs, and it should be first priority for me in this phase.

**Comment by bryanyang0528** [comment]
BTW, KSQL released their official API docs: [https://docs.confluent.io/current/ksql/docs/api.html](https://docs.confluent.io/current/ksql/docs/api.html) It's helpful for our further plan
