### ISSUE TITLE
Which KSQL version is supported? 

### ISSUE THREAD

**Issue by kaiwaehner** [bryanyang0528/ksql-python#36]
Please explain in the readme which KSQL version is supported and tested. 

Important as KSQL is evolving fast and was not backwards compatible in the past (I think this changed now with its GA release).

I wonder if it already works with KSQL 5.0 (part of Confluent Platform 5.0)?

**Comment by bryanyang0528** [comment]
Thanks to @sebastianneubauer, KSQL-python is migrated to 5.x. Please try it. Any feedbacks are welcome.

**Comment by kaiwaehner** [comment]
Works great. Thank you!
