### ISSUE TITLE
How to do a JOIN with the Python API?

### ISSUE THREAD

**Issue by kaiwaehner** [bryanyang0528/ksql-python#53]
How do I do a JOIN with the Python API?

Here are my STREAM and TABLE:

```
client.create_stream(table_name='creditcardfraud_source',
                     columns_type=['Id bigint', 'Timestamp varchar', 'User varchar', 'Time int', 'V1 double', 'V2 double', 'V3 double', 'V4 double', 'V5 double', 'V6 double', 'V7 double', 'V8 double', 'V9 double', 'V10 double', 'V11 double', 'V12 double', 'V13 double', 'V14 double', 'V15 double', 'V16 double', 'V17 double', 'V18 double', 'V19 double', 'V20 double', 'V21 double', 'V22 double', 'V23 double', 'V24 double', 'V25 double', 'V26 double', 'V27 double', 'V28 double', 'Amount double', 'Class string'],
                     topic='creditcardfraud_source',
                     value_format='DELIMITED')

client.create_table(table_name='users',
                     columns_type=['userid varchar', 'gender varchar', 'regionid varchar'],
                     topic='users',
                     key='userid',
                     value_format='AVRO')
```

Not sure how to configure the JOIN? Or is this not possible yet?

**Comment by bryanyang0528** [comment]
Because JOIN is a quite complex feature including multiple tables, join keys, etc..., maybe you can try to write a SQL syntax directly before implementing a JOIN API.

**Comment by kaiwaehner** [comment]
@bryanyang0528 Makes sense!

I think to use ksql-python in real projects, at least the workaround using client.ksql should work. 

The following example works in KSQL CLI, but not in ksql-python:

`client.ksql('CREATE STREAM creditcardfraud_per_user WITH (VALUE_FORMAT='AVRO', KAFKA_TOPIC='creditcardfraud_per_user') AS SELECT Time, Amount, Class FROM creditcardfraud_source c INNER JOIN USERS u on c.user = u.userid WHERE u.USERID = 1')`

Did you get any JOIN example working?
Maybe this is the same problem as with the "SET auto.offset.reset" issue?

**Comment by bryanyang0528** [comment]
@kaiwaehner  I can join tables like this:
```
>>> client.ksql("CREATE TABLE creditcardfraud_per_user WITH (VALUE_FORMAT='AVRO', KAFKA_TOPIC='creditcardfraud_per_user') AS SELECT * FROM creditcardfra
ud_source c INNER JOIN USERS u on c.userid = u.userid WHERE u.USERID = 1")
[{'@type': 'currentStatus', 'statementText': "CREATE TABLE creditcardfraud_per_user WITH (VALUE_FORMAT='AVRO', KAFKA_TOPIC='creditcardfraud_per_user') A
S SELECT * FROM creditcardfraud_source c INNER JOIN USERS u on c.userid = u.userid WHERE u.USERID = 1;", 'commandId': 'table/CREDITCARDFRAUD_PER_USER/cr
eate', 'commandStatus': {'status': 'SUCCESS', 'message': 'Table created and running'}}]
>>> 
``` 

Maybe you can try use `"` instead of `'` for wrapping the sql string

**Comment by kaiwaehner** [comment]
This works, thank you.

I will also update the README of this project and add an example.
