### ISSUE TITLE
pip package broken **Still get an error:**

### ISSUE THREAD

**Issue by crocus** [bryanyang0528/ksql-python#58]
**Still get an error:**
/opt/anaconda3/bin/python -m pip install --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --trusted-host pypi.org  --upgrade ksql
Collecting ksql
  Downloading https://files.pythonhosted.org/packages/98/9f/1187d5bf9ab6e68c23fde44f93df2e1aae94083e1c6608a299aa1c6a99f5/ksql-0.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-cwddsvt7/ksql/setup.py", line 52, in <module>
        install_requires=get_install_requirements("requirements.txt"),
      File "/tmp/pip-install-cwddsvt7/ksql/setup.py", line 27, in get_install_requirements
        content = open(os.path.join(os.path.dirname(__file__), path)).read()
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-cwddsvt7/ksql/requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-cwddsvt7/ksql/

_Originally posted by @crocus in https://github.com/bryanyang0528/ksql-python/issues/51#issuecomment-462763141_

**Comment by bryanyang0528** [comment]
Thank you for reporting this. I'll test it in these days.

**Comment by bryanyang0528** [comment]
It's ok now.
![image](https://user-images.githubusercontent.com/5171607/53298370-e5d15900-3867-11e9-85b3-25502fbc5821.png)
