### ISSUE TITLE
KSQL RESTful API Basic Authentication support missing

### ISSUE THREAD

**Issue by HafizAtWork** [bryanyang0528/ksql-python#61]
Hi,

Our KSQL server is enabled with Basic http authentication(username:password). I don't find the relevant options while creating the client. i.e. ksql.KSQLAPI(<serverIP:port>)

Curl with param **-u** <username>:<password> works fine for me.

**Comment by bryanyang0528** [comment]
Sorry for the late reply.
#64  is merged. You can find related docs in README
