### ISSUE TITLE
query timeout if i dont put limit in query. 

### ISSUE THREAD

**Issue by varunajmera0** [bryanyang0528/ksql-python#63]
How can we get continues data from stream
client = KSQLAPI('http://127.0.0.1:8088')
streamProperties = {"ksql.streams.auto.offset.reset": "earliest"}
   def cal():
    def events():
        query_string="select * from trend_news_stream emit changes;"
        q = client.query(query_string, stream_properties=streamProperties, idle_timeout=10)
        for c in q:
            yield c
    return Response(events(), mimetype="text/event-stream")

**Comment by romainr** [comment]
Check https://github.com/bryanyang0528/ksql-python/pull/60

**Comment by bryanyang0528** [comment]
fixed in #60 and #67
