### ISSUE TITLE
[Question] How to delete topic ?

### ISSUE THREAD

**Issue by scheung38** [bryanyang0528/ksql-python#84]
Use kafka-topics.sh --delete to delete remove-me topic.

$ ./bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic remove-me
Topic remove-me is marked for deletion.
Note: This will have no impact if delete.topic.enable is not set to true.

But how to do this using this repo?

**Comment by bryanyang0528** [comment]
Hi @scheung38,
This repo is an API wrapper for KSQL, not Kafka, so this repo can not delete the topic directly unless KSQL API supports this function.
