### ISSUE TITLE
ksql.upload.FileUpload.upload() gives InvalidQueryError

### ISSUE THREAD

**Issue by qtfkwk** [bryanyang0528/ksql-python#98]
The following snippet from [ksql/upload.py:38](https://github.com/bryanyang0528/ksql-python/blob/9cd96cdb8bf1fdd2ef1e163cc07de854ffc39337/ksql/upload.py#L38) has a problem which is causing the InvalidQueryError exception to be raised when parsing a file that has one statement per line and each statement ends with a semicolon. The issue seems to be caused by `rule` being an empty string after yielding, and then the last 2 lines check that the empty `rule` ends with a semicolon... *but the last rule already yielded!*

Believe the fix is to simply delete these lines.

```python
    def get_rules_list(self, ksqlfile):
        with open(ksqlfile) as rf:
            rule = ""

            for line in rf:
                rule = rule + " " + line.strip()

                if rule[-1:] == ";":
                    yield rule
                    rule = ""

            if rule[-1:] != ";":
                raise InvalidQueryError(rule)
```

**Comment by qtfkwk** [comment]
https://github.com/bryanyang0528/ksql-python/pull/99

**Comment by Ga11u** [comment]
Is there any updates on this issue?

I agree with you. The code does not make sense. After reading all lines in the file the `rule` will be equal to `""` .

Therefore this lines will always rise and error:

``` py
if rule[-1:] != ";":
    raise InvalidQueryError(rule)
```

If these lines are equal to something else than `""`  that would mean the last query was invalid, and if it is equal to `";"` , this means the last rule has not bien yield, but this second scenario cannot happend within the current code. Hence, these lines should al least be changed to:

``` py
if rule[-1:] != "":
    raise InvalidQueryError(rule)
```
